### PR TITLE
EARTH-409: Added simplesamlphp and externalauth modules with split enable

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Adds two new modules just for production
- Fixes up some config split settings

# Steps to Test

1. Check out this branch
2. Run `drush cim` to import config 
3. Ensure the simpesamlphp_auth module is still disabled
4. Run `drush csim prod -y` 
5. Ensure the simpesamlphp_auth and externalauth modules are enabled

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by ksharp-drupal** [comment]
After running 'drush csim prod -y' (which, btw, first required a 'drush cr all' to enable the 'config_split' module, I get the following error when I try to go the site on my local system:

The website encountered an unexpected error. Please try again later.
AssertionError: in assert() (line 24 of /WWW/se3_blt/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Simple.php).

assert('is_string($authSource)') (Line: 24)
SimpleSAML_Auth_Simple->__construct(NULL) (Line: 59)
Drupal\simplesamlphp_auth\Service\SimplesamlphpAuthManager->__construct(Object) (Line: 268)
Drupal\Component\DependencyInjection\Container->createService(Array, 'simplesamlphp_auth.manager') (Line: 177)
Drupal\Component\DependencyInjection\Container->get('simplesamlphp_auth.manager', 1) (Line: 494)
Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array) (Line: 236)
Drupal\Component\DependencyInjection\Container->createService(Array, 'simplesamlphp_auth_event_subscriber') (Line: 177)
Drupal\Component\DependencyInjection\Container->get('simplesamlphp_auth_event_subscriber') (Line: 108)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.request', Object) (Line: 125)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 656)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)

**Comment by sherakama** [comment]
@ksharp-drupal,

I suppose I should have included the config as well. It is now attached and ready for review again.

**Comment by ksharp-drupal** [comment]
I still got the same error until I ran two additional steps (on my development system):

4a. blt simplesamlphp:init
4b. cp ${project.root}/simplesamlphp/config/* ${project.root}/vendor/simplesamlphp/simplesamlphp/config

At that point 5, showing the modules are enabled, works. 
I think we should hold off on approving this until I know the .htaccess file and simplesaml symlink will be preserved.

**Comment by sherakama** [comment]
@ksharp-drupal 

Thanks for reviewing that. I do agree we should hold off on merging until we can get the additional items sorted out. This configuration should only be enabled on production which should help defend against the other environments but it would be good to have it polished.

Please see: https://github.com/stanford-earth/SE3_BLT/pull/73 for a first pass at getting the additional items in place.

**Comment by ksharp-drupal** [comment]
Yes, thanks, I was just looking at that. I'll keep you posted.

**Comment by ksharp-drupal** [comment]
I've been playing with the "post-drupal-scaffold-cmd" hook to patch .htaccess file and symlink to simplesaml. Does not recognize config-split, but patch will not harm functionality on dev or stage. Will try to check in for review today or tomorrow.

**Comment by sherakama** [comment]
Forgive me but what does not recognize config-split and which patch are you referring to?

**Comment by sherakama** [comment]
Moved to: https://github.com/stanford-earth/SE3_BLT/pull/80

**Pull request closed without merging**
