### PR TITLE
EARTH-144

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW 

# Summary
- Adds and enables the stanford_department content type

# Needed By (Date)
- End of this sprint (July 29th)

# Urgency
- Moderate

# Steps to Test

0. Save any work in progress you may have.
1. Check out this branch.
2. Run `composer update` to download the new module
3. Run `drush cim` to import default config
4. Run `drush csim local` to import local config
4b. Run `drush features-import-all` to import the feature config
5. Navigate to `/node/add` to confirm there is a Department option
6. Create a new department page by adding a few paragraphs. There should be all of the currently installed options available.

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/EARTH-145 Department node template
- @koppieesq 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by ksharp-drupal** [comment]
When I run 'composer update', I get a series of "This package has modified files" followed by "Discard changes [y,n,v,d,s,?]?" prompts. I've tried a couple of variations, but it always ends with the Department Page feature uninstalled with no ability to install or enable it.

**Comment by sherakama** [comment]
@ksharp-drupal You are probably seeing the following message:
```
Updating drupal/components dev-1.x (bc12562 => bc12562):     The package has modified files:
    M src/Template/Loader/ComponentLibraryLoader.php
    Discard changes [y,n,v,d,s,?]?
```

This is because of a patch that has been applied. It is fine to discard the changes and enter `y` at the prompt.

**Comment by ksharp-drupal** [comment]
Needed to take the extra step, after step 4 in above "Steps to Test" of going to Features and import missing configuration, after which new content type appears; however, simple_sitemap.bundle_settings.node.stanford_department is still missing after the import step;

**Comment by sherakama** [comment]
Oh shoot, you are right. So that is a fun little gotcha. Looks like the config import without the features import un-does the stuff that is in the feature. That is a good little workflow item to know.

I guess I should have added to step 4 `drush features-import-all` 
That will turn up some overrides as the config in /config/default will not always match the feature state during development. Once we get a stable release cut we will be sure to sync the default config up with what is in the features. The deploy process does this in the following order

1. Import config/default
2. Import config/[environment]
3. Import feature config

So features will always rule and cannot be overridden.

**Comment by sherakama** [comment]
So a much quicker way than to execute all of those commands would be to do the following:

1. Check out branch
2. Run `composer update --prefer-source`
3. Run `blt local:refresh`

The local refresh has the aforementioned deployment steps built in to it but it also wipes your db so it might not be what you want each time.

**Comment by sherakama** [comment]
Ok, I see where you say the config item is missing. This is a false positive as the config item is there it is just in the feature and not in the default site config. I have included those config files in the default config now. That should clean up any missing or odd diff messages.

**Comment by sherakama** [comment]
@ksharp-drupal Please have another review.

**Comment by ksharp-drupal** [comment]
All good now. Squashing and merging.

**Comment by sherakama** [comment]
Great! Thanks for catching those issues. I will update the working document and encapsulate what we learned here.

**Pull request merged**
